import iMacDesktop from "./images/iMac.jpg";
import MacMini from "./images/MacMini.jpg";
import DellXPSDesktop from "./images/DellXPS-Desktop.jpg";
import HPDesktop from "./images/HP-Desktop.jpg";


const listProducts = [
	{
		id: 		"AA0001",
		category: 	"Desktop",
		type: 		"iMac",
		product: 	"24inch 4.5 Retina Display",
		description:"iMac-ChipM1 8-Core CPU & 7-Core GPU 8GB Unified memory 256GB Storage",
		price: 		1899,
		image: 		iMacDesktop,
		quanity:	1,
	},
	{
		id: 		"AA0002",
		category: 	"Desktop",
		type: 		"iMac",
		product: 	"24inch 4.5 Retina Display",
		description:"iMac-ChipM1 8-Core CPU & 8-Core GPU 16GB Unified memory 256GB Storage",
		price: 		2099,
		image: 		iMacDesktop,
		quanity:	1,
	},
	{
		id: 		"AA0003",
		category: 	"Desktop",
		type: 		"iMac",
		product: 	"24inch 4.5 Retina Display",
		description:"iMac-ChipM1 8-Core CPU & 8-Core GPU 16GB Unified memory 512GB Storage",
		price: 		2299,
		image: 		iMacDesktop,
		quanity:	1,
	},
	{
		id: 		"AA0004",
		category: 	"Desktop",
		type: 		"iMac",
		product: 	"24inch 4.5 Retina Display",
		description:"iMac-ChipM1 8-Core CPU & 8-Core GPU 16GB Unified memory 1TB Storage",
		price: 		2599,
		image: 		iMacDesktop,
		quanity:	1,
	},
	{
		id: 		"AA0005",
		category: 	"Desktop",
		type: 		"Mac Mini",
		product: 	"MacMini Apple Chip M1",
		description:"With 8-Core CPU & 8-Core GPU 8GB Unified memory 256GB Storage",
		price: 		 929,
		image: 		MacMini,
		quanity:	1,
	},
	{
		id: 		"AA0006",
		category: 	"Desktop",
		type: 		"Mac Mini",
		product: 	"MacMini Apple Chip M1",
		description:"With 8-Core CPU & 8-Core GPU 16GB Unified memory 256GB Storage",
		price: 		 1199,
		image: 		MacMini,
		quanity:	1,
	},
	{
		id: 		"AA0007",
		category: 	"Desktop",
		type: 		"Mac Mini",
		product: 	"MacMini Apple Chip M1",
		description:"With 8-Core CPU & 8-Core GPU 16GB Unified memory 512GB Storage",
		price: 		 1499,
		image: 		MacMini,
		quanity:	1,
	},
	{
		id: 		"AA0008",
		category: 	"Desktop",
		type: 		"Mac Mini",
		product: 	"MacMini Apple Chip M1",
		description:"With 8-Core CPU & 8-Core GPU 16GB Unified memory 1TB Storage",
		price: 		 1899,
		image: 		MacMini,
		quanity:	1,
	},
	{				
		id: 		"AA0009",
		category: 	"Desktop",
		type: 		"Dell",
		product: 	"Dell XPS Gen12th",
		description:"With 12-CoreCPU & 3070VGA 16GB Unified memory 512SSD",
		price: 		 1999,
		image: 		DellXPSDesktop,
		quanity:	1,
	},
	{				
		id: 		"AA0010",
		category: 	"Desktop",
		type: 		"Dell",
		product: 	"Dell XPS Gen12th",
		description:"With 12-CoreCPU & 3070VGA 32GB Unified memory 512SSD",
		price: 		 2099,
		image: 		DellXPSDesktop,
		quanity:	1,
	},
		{				
		id: 		"AA0011",
		category: 	"Desktop",
		type: 		"Dell",
		product: 	"Dell XPS Gen12th",
		description:"With 12-CoreCPU & 3070VGA 32GB Unified memory 1TBSSD",
		price: 		 2399,
		image: 		DellXPSDesktop,
		quanity:	1,
	},
	{				
		id: 		"AA0012",
		category: 	"Desktop",
		type: 		"Dell",
		product: 	"Dell XPS Gen12th",
		description:"With 12-CoreCPU & 3070VGA 32GB Unified memory 2TBSSD",
		price: 		 2699,
		image: 		DellXPSDesktop,
		quanity:	1,
	},
	{				
		id: 		"AA0013",
		category: 	"Desktop",
		type: 		"HP",
		product: 	"HP Workstation Gen12th",
		description:"With 12-CoreCPU & 3080VGA 16GB Unified memory 1TBSSD",
		price: 		 2299,
		image: 		HPDesktop,
		quanity:	1,
	},
	{				
		id: 		"AA0014",
		category: 	"Desktop",
		type: 		"HP",
		product: 	"HP Workstation Gen12th",
		description:"With 12-CoreCPU & 3080VGA 32GB Unified memory 1TBSSD",
		price: 		 2599,
		image: 		HPDesktop,
		quanity:	1,
	},
	{				
		id: 		"AA0015",
		category: 	"Desktop",
		type: 		"HP",
		product: 	"HP Workstation Gen12th",
		description:"With 12-CoreCPU & 3080VGA 32GB Unified memory 2TBSSD",
		price: 		 2799,
		image: 		HPDesktop,
		quanity:	1,
	},
	{				
		id: 		"AA0016",
		category: 	"Desktop",
		type: 		"HP",
		product: 	"HP Workstation Gen12th",
		description:"With 12-CoreCPU & 3080VGA 64GB Unified memory 2TBSSD",
		price: 		 3299,
		image: 		HPDesktop,
		quanity:	1,
	},
];

export default listProducts;