import iMacDesktop from "./images/iMac.jpg";
import iMacDesktop2 from "./images/iMac2.jpg";

import MacMini from "./images/MacMini.jpg";
import MacMini2 from "./images/mac-mini2.jpg";

import DellXPSDesktop from "./images/DellXPS-Desktop.jpg";
import HPDesktop from "./images/HP-Desktop.jpg";
import AcerDesktop from "./images/ACER-Desktop.jpg";
import ASUSDesktop from "./images/ASUS-Desktop.jpg";
import ACERDESKTOPPREDATOR from "./images/Acer-predator.jpeg";

const listProducts = [
	{
		id: "AA0001",
		category: "Desktop",
		type: "iMac",
		product: "24inch 4.5 Retina Display",
		description:
			"iMac-ChipM1 8-Core CPU & 7-Core GPU 8GB Unified memory 256GB Storage",
		price: 1899,
		image: iMacDesktop2,
		quanity: 1,
	},
	{
		id: "AA0002",
		category: "Desktop",
		type: "iMac",
		product: "24inch 4.5 Retina Display",
		description:
			"iMac-ChipM1 8-Core CPU & 8-Core GPU 16GB Unified memory 256GB Storage",
		price: 2099,
		image: iMacDesktop2,
		quanity: 1,
	},
	{
		id: "AA0003",
		category: "Desktop",
		type: "iMac",
		product: "24inch 4.5 Retina Display",
		description:
			"iMac-ChipM1 8-Core CPU & 8-Core GPU 16GB Unified memory 512GB Storage",
		price: 2299,
		image: iMacDesktop,
		quanity: 1,
	},
	{
		id: "AA0004",
		category: "Desktop",
		type: "iMac",
		product: "24inch 4.5 Retina Display",
		description:
			"iMac-ChipM1 8-Core CPU & 8-Core GPU 16GB Unified memory 1TB Storage",
		price: 2599,
		image: iMacDesktop,
		quanity: 1,
	},
	{
		id: "A10001",
		category: "Desktop",
		type: "iMac",
		product: "24inch 4.5 Retina Display",
		description:
			"iMac-ChipM1 8-Core CPU & 8-Core GPU 24GB Unified memory 256GB Storage",
		price: 2299,
		image: iMacDesktop2,
		quanity: 1,
	},
	{
		id: "A10002",
		category: "Desktop",
		type: "iMac",
		product: "24inch 4.5 Retina Display",
		description:
			"iMac-ChipM1 8-Core CPU & 8-Core GPU 24GB Unified memory 512GB Storage",
		price: 2499,
		image: iMacDesktop,
		quanity: 1,
	},
	{
		id: "A10003",
		category: "Desktop",
		type: "iMac",
		product: "24inch 4.5 Retina Display",
		description:
			"iMac-ChipM1 8-Core CPU & 8-Core GPU 24GB Unified memory 1TB Storage",
		price: 2799,
		image: iMacDesktop2,
		quanity: 1,
	},
	{
		id: "A10004",
		category: "Desktop",
		type: "iMac",
		product: "24inch 4.5 Retina Display",
		description:
			"iMac-ChipM1 8-Core CPU & 8-Core GPU 24GB Unified memory 2TB Storage",
		price: 2999,
		image: iMacDesktop,
		quanity: 1,
	},
	{
		id: "A10005",
		category: "Desktop",
		type: "iMac",
		product: "24inch 4.5 Retina Display",
		description:
			"iMac-ChipM1 10-Core CPU & 10-Core GPU 24GB Unified memory 256GB Storage",
		price: 2339,
		image: iMacDesktop2,
		quanity: 1,
	},
	{
		id: "A10006",
		category: "Desktop",
		type: "iMac",
		product: "24inch 4.5 Retina Display",
		description:
			"iMac-ChipM1 10-Core CPU & 10-Core GPU 24GB Unified memory 512GB Storage",
		price: 2669,
		image: iMacDesktop,
		quanity: 1,
	},
	{
		id: "A10007",
		category: "Desktop",
		type: "iMac",
		product: "24inch 4.5 Retina Display",
		description:
			"iMac-ChipM1 10-Core CPU & 10-Core GPU 24GB Unified memory 1TB Storage",
		price: 2888,
		image: iMacDesktop,
		quanity: 1,
	},
	{
		id: "AA0005",
		category: "Desktop",
		type: "Mac-Mini",
		product: "MacMini Apple Chip M1",
		description:
			"With 8-Core CPU & 8-Core GPU 8GB Unified memory 256GB Storage",
		price: 929,
		image: MacMini,
		quanity: 1,
	},
	{
		id: "AA0006",
		category: "Desktop",
		type: "Mac-Mini",
		product: "MacMini Apple Chip M1",
		description:
			"With 8-Core CPU & 8-Core GPU 16GB Unified memory 256GB Storage",
		price: 1199,
		image: MacMini2,
		quanity: 1,
	},
	{
		id: "AA0007",
		category: "Desktop",
		type: "Mac-Mini",
		product: "MacMini Apple Chip M1",
		description:
			"With 8-Core CPU & 8-Core GPU 16GB Unified memory 512GB Storage",
		price: 1499,
		image: MacMini,
		quanity: 1,
	},
	{
		id: "AA0008",
		category: "Desktop",
		type: "Mac-Mini",
		product: "MacMini Apple Chip M1",
		description: "With 8-Core CPU & 8-Core GPU 16GB Unified memory 1TB Storage",
		price: 1899,
		image: MacMini2,
		quanity: 1,
	},
	{
		id: "AA00080",
		category: "Desktop",
		type: "Mac-Mini",
		product: "MacMini Apple Chip M1",
		description: "With 8-Core CPU & 8-Core GPU 16GB Unified memory 2TB Storage",
		price: 2188,
		image: MacMini,
		quanity: 1,
	},
	{
		id: "AA00081",
		category: "Desktop",
		type: "Mac-Mini",
		product: "MacMini Apple Chip M1",
		description: "With 8-Core CPU & 8-Core GPU 16GB Unified memory 4TB Storage",
		price: 2688,
		image: MacMini2,
		quanity: 1,
	},
	{
		id: "AA00082",
		category: "Desktop",
		type: "Mac-Mini",
		product: "MacMini Apple Chip M1",
		description:
			"With 10-Core CPU & 10-Core GPU 24GB Unified memory 512SSD Storage",
		price: 2266,
		image: MacMini,
		quanity: 1,
	},
	{
		id: "AA00083",
		category: "Desktop",
		type: "Mac-Mini",
		product: "MacMini Apple Chip M1",
		description:
			"With 10-Core CPU & 10-Core GPU 24GB Unified memory 1TB Storage",
		price: 2788,
		image: MacMini2,
		quanity: 1,
	},
	{
		id: "AA00084",
		category: "Desktop",
		type: "Mac-Mini",
		product: "MacMini Apple Chip M1",
		description:
			"With 10-Core CPU & 10-Core GPU 24GB Unified memory 2TB Storage",
		price: 2889,
		image: MacMini,
		quanity: 1,
	},
	{
		id: "AA0009",
		category: "Desktop",
		type: "Dell",
		product: "Dell XPS Gen12th",
		description: "With 12-CoreCPU & 3070VGA 16GB Unified memory 512SSD",
		price: 1999,
		image: DellXPSDesktop,
		quanity: 1,
	},
	{
		id: "AA0010",
		category: "Desktop",
		type: "Dell",
		product: "Dell XPS Gen12th",
		description: "With 12-CoreCPU & 3070VGA 32GB Unified memory 512SSD",
		price: 2099,
		image: DellXPSDesktop,
		quanity: 1,
	},
	{
		id: "AA0011",
		category: "Desktop",
		type: "Dell",
		product: "Dell XPS Gen12th",
		description: "With 12-CoreCPU & 3070VGA 32GB Unified memory 1TBSSD",
		price: 2399,
		image: DellXPSDesktop,
		quanity: 1,
	},
	{
		id: "AA0012",
		category: "Desktop",
		type: "Dell",
		product: "Dell XPS Gen12th",
		description: "With 12-CoreCPU & 3070VGA 32GB Unified memory 2TBSSD",
		price: 2699,
		image: DellXPSDesktop,
		quanity: 1,
	},
	{
		id: "AA00120",
		category: "Desktop",
		type: "Dell",
		product: "Dell XPS Gen12th",
		description: "With 12-CoreCPU & 2060VGA 16GB Unified memory 512SSD",
		price: 1699,
		image: DellXPSDesktop,
		quanity: 1,
	},
	{
		id: "AA00121",
		category: "Desktop",
		type: "Dell",
		product: "Dell XPS Gen12th",
		description: "With 12-CoreCPU & 2060VGA 32GB Unified memory 512SSD",
		price: 1799,
		image: DellXPSDesktop,
		quanity: 1,
	},
	{
		id: "AA00122",
		category: "Desktop",
		type: "Dell",
		product: "Dell XPS Gen11th",
		description: "With 12-CoreCPU & 2060VGA 16GB Unified memory 512SSD",
		price: 1499,
		image: DellXPSDesktop,
		quanity: 1,
	},
	{
		id: "AA00123",
		category: "Desktop",
		type: "Dell",
		product: "Dell XPS Gen11th",
		description: "With 12-CoreCPU & 2060VGA 16GB Unified memory 1TBSSD",
		price: 1879,
		image: DellXPSDesktop,
		quanity: 1,
	},
	{
		id: "AA00124",
		category: "Desktop",
		type: "Dell",
		product: "Dell XPS Gen11th",
		description: "With 12-CoreCPU & 2060VGA 64GB Unified memory 2TBSSD",
		price: 2679,
		image: DellXPSDesktop,
		quanity: 1,
	},
	{
		id: "AA0013",
		category: "Desktop",
		type: "HP",
		product: "HP Workstation Gen12th",
		description: "With 12-CoreCPU & 3080VGA 16GB Unified memory 1TBSSD",
		price: 2299,
		image: HPDesktop,
		quanity: 1,
	},
	{
		id: "AA0014",
		category: "Desktop",
		type: "HP",
		product: "HP Workstation Gen12th",
		description: "With 12-CoreCPU & 3080VGA 32GB Unified memory 1TBSSD",
		price: 2599,
		image: HPDesktop,
		quanity: 1,
	},
	{
		id: "AA0015",
		category: "Desktop",
		type: "HP",
		product: "HP Workstation Gen12th",
		description: "With 12-CoreCPU & 3080VGA 32GB Unified memory 2TBSSD",
		price: 2799,
		image: HPDesktop,
		quanity: 1,
	},
	{
		id: "AA0016",
		category: "Desktop",
		type: "HP",
		product: "HP Workstation Gen12th",
		description: "With 12-CoreCPU & 3080VGA 64GB Unified memory 2TBSSD",
		price: 3299,
		image: HPDesktop,
		quanity: 1,
	},
	{
		id: "AA0017",
		category: "Desktop",
		type: "HP",
		product: "HP Workstation Gen11th",
		description: "With 10-CoreCPU & 2060VGA 16GB Unified memory 512SSD",
		price: 1289,
		image: HPDesktop,
		quanity: 1,
	},
	{
		id: "AA0018",
		category: "Desktop",
		type: "HP",
		product: "HP Workstation Gen11th",
		description: "With 10-CoreCPU & 2060VGA 32GB Unified memory 512SSD",
		price: 1689,
		image: HPDesktop,
		quanity: 1,
	},
	{
		id: "AA0019",
		category: "Desktop",
		type: "HP",
		product: "HP Workstation Gen11th",
		description: "With 10-CoreCPU & 2060VGA 32GB Unified memory 1TB",
		price: 1889,
		image: HPDesktop,
		quanity: 1,
	},
	{
		id: "AA0020",
		category: "Desktop",
		type: "HP",
		product: "HP Workstation Gen11th",
		description: "With 10-CoreCPU & 2060VGA 32GB Unified memory 1TB",
		price: 2099,
		image: HPDesktop,
		quanity: 1,
	},
	{
		id: "AA0021",
		category: "Desktop",
		type: "HP",
		product: "HP Workstation Gen11th",
		description: "With 10-CoreCPU & 2060VGA 32GB Unified memory 2TB",
		price: 2199,
		image: HPDesktop,
		quanity: 1,
	},
	{
		id: "AA0022",
		category: "Desktop",
		type: "Acer",
		product: "Acer Nitro Gen11th",
		description: "With 10-CoreCPU & 2060VGA 8GB DDRAM4 256SSD",
		price: 1229,
		image: AcerDesktop,
		quanity: 1,
	},
	{
		id: "AA00220",
		category: "Desktop",
		type: "Acer",
		product: "Acer Predator Gen12th",
		description: "With 12-CoreCPU & 3080VGA 32GB DDRAM4 1TB",
		price: 3699,
		image: ACERDESKTOPPREDATOR,
		quanity: 1,
	},
	{
		id: "AA0023",
		category: "Desktop",
		type: "Acer",
		product: "Acer Nitro Gen11th",
		description: "With 10-CoreCPU & 2060VGA 16GB DDRAM4 256SSD",
		price: 1489,
		image: AcerDesktop,
		quanity: 1,
	},
	{
		id: "AA0024",
		category: "Desktop",
		type: "Acer",
		product: "Acer Nitro Gen11th",
		description: "With 10-CoreCPU & 2060VGA 16GB DDRAM4 512SSD",
		price: 1689,
		image: AcerDesktop,
		quanity: 1,
	},
	{
		id: "AA0025",
		category: "Desktop",
		type: "Acer",
		product: "Acer Nitro Gen11th",
		description: "With 10-CoreCPU & 2060VGA 32GB DDRAM4 512SSD",
		price: 1889,
		image: AcerDesktop,
		quanity: 1,
	},
	{
		id: "AA0026",
		category: "Desktop",
		type: "Acer",
		product: "Acer Nitro Gen12th",
		description: "With 10-CoreCPU & 3060VGA 16GB DDRAM4 512SSD",
		price: 2009,
		image: AcerDesktop,
		quanity: 1,
	},
	{
		id: "AA0027",
		category: "Desktop",
		type: "Acer",
		product: "Acer Nitro Gen12th",
		description: "With 10-CoreCPU & 3060VGA 16GB DDRAM4 512SSD",
		price: 2009,
		image: AcerDesktop,
		quanity: 1,
	},
	{
		id: "AA0028",
		category: "Desktop",
		type: "Acer",
		product: "Acer Nitro Gen12th",
		description: "With 10-CoreCPU & 3060VGA 32GB DDRAM4 1TB",
		price: 2559,
		image: AcerDesktop,
		quanity: 1,
	},
	{
		id: "AA0029",
		category: "Desktop",
		type: "Acer",
		product: "Acer Nitro Gen12th",
		description: "With 10-CoreCPU & 3060VGA 32GB DDRAM4 2TB",
		price: 2779,
		image: AcerDesktop,
		quanity: 1,
	},
	{
		id: "AA0030",
		category: "Desktop",
		type: "Acer",
		product: "Acer Nitro Gen12th",
		description: "With 10-CoreCPU & 3070VGA 32GB DDRAM4 2TB",
		price: 2999,
		image: AcerDesktop,
		quanity: 1,
	},
	{
		id: "AA0031",
		category: "Desktop",
		type: "Acer",
		product: "Acer Nitro Gen12th",
		description: "With 10-CoreCPU & 3080VGA 64GB DDRAM4 2TB",
		price: 4999,
		image: AcerDesktop,
		quanity: 1,
	},
	{
		id: "AA0032",
		category: "Desktop",
		type: "Asus",
		product: "ASUS ROG Strix Gen11th",
		description: "With 10-CoreCPU & 2060VGA 16GB DDRAM4 512SSD",
		price: 1299,
		image: ASUSDesktop,
		quanity: 1,
	},
	{
		id: "AA0033",
		category: "Desktop",
		type: "Asus",
		product: "ASUS ROG Strix Gen11th",
		description: "With 10-CoreCPU & 2060VGA 32GB DDRAM4 512SSD",
		price: 1499,
		image: ASUSDesktop,
		quanity: 1,
	},
	{
		id: "AA0034",
		category: "Desktop",
		type: "Asus",
		product: "ASUS ROG Strix Gen11th",
		description: "With 10-CoreCPU & 2060VGA 32GB DDRAM4 1TB",
		price: 1889,
		image: ASUSDesktop,
		quanity: 1,
	},
	{
		id: "AA0035",
		category: "Desktop",
		type: "Asus",
		product: "ASUS ROG Strix Gen11th",
		description: "With 10-CoreCPU & 2070VGA 32GB DDRAM4 1TB",
		price: 1999,
		image: ASUSDesktop,
		quanity: 1,
	},
	{
		id: "AA0036",
		category: "Desktop",
		type: "Asus",
		product: "ASUS ROG Strix Gen12th",
		description: "With 12-CoreCPU & 3060VGA 16GB DDRAM4 512SSD",
		price: 2099,
		image: ASUSDesktop,
		quanity: 1,
	},
	{
		id: "AA0037",
		category: "Desktop",
		type: "Asus",
		product: "ASUS ROG Strix Gen12th",
		description: "With 12-CoreCPU & 3060VGA 32GB DDRAM4 512SSD",
		price: 2299,
		image: ASUSDesktop,
		quanity: 1,
	},
	{
		id: "AA0038",
		category: "Desktop",
		type: "Asus",
		product: "ASUS ROG Strix Gen12th",
		description: "With 12-CoreCPU & 3060VGA 32GB DDRAM4 1TB",
		price: 2499,
		image: ASUSDesktop,
		quanity: 1,
	},
	{
		id: "AA0039",
		category: "Desktop",
		type: "Asus",
		product: "ASUS ROG Strix Gen12th",
		description: "With 12-CoreCPU & 3060VGA 32GB DDRAM4 2TB",
		price: 2599,
		image: ASUSDesktop,
		quanity: 1,
	},
	{
		id: "AA0040",
		category: "Desktop",
		type: "Asus",
		product: "ASUS ROG Strix Gen12th",
		description: "With 12-CoreCPU & 3060VGA 64GB DDRAM4 2TB",
		price: 2899,
		image: ASUSDesktop,
		quanity: 1,
	},
	{
		id: "AA0041",
		category: "Desktop",
		type: "Asus",
		product: "ASUS ROG Strix Gen12th",
		description: "With 12-CoreCPU & 3070VGA 32GB DDRAM4 2TB",
		price: 2999,
		image: ASUSDesktop,
		quanity: 1,
	},
	{
		id: "AA0042",
		category: "Desktop",
		type: "Asus",
		product: "ASUS ROG Strix Gen12th",
		description: "With 12-CoreCPU & 3080VGA 64GB DDRAM4 4TB",
		price: 4779,
		image: ASUSDesktop,
		quanity: 1,
	},
];

export default listProducts;
