import iMacDesktop from "./images/iMac.jpg";
import iMacDesktop2 from "./images/iMac2.jpg";
import MacMini from "./images/MacMini.jpg";
import MacMini2 from "./images/mac-mini2.jpg";
import DellXPSDesktop from "./images/DellXPS-Desktop.jpg";
import DellXPSDesktop2 from "./images/DellXPS-Desktop2.jpg";
import DellXPSDesktop3 from "./images/DellXPS-Desktop3.jpg";
import HPDesktop from "./images/HP-Desktop.jpg";
import HPDesktop2 from "./images/HP-Desktop2.jpg";

import AcerDesktop from "./images/ACER-Desktop.jpg";
import ASUSDesktop from "./images/ASUS-Desktop.jpg";
import ASUSDesktop2 from "./images/ASUS-Desktop2.jpg";
import ASUSDesktop3 from "./images/ASUS-Desktop3.jpg";

import ACERDESKTOPPREDATOR from "./images/Acer-predator.jpeg";
import MacbookProLaptop from "./images/MacbookPro-Laptop.jpg";
import MacbookProLaptop2 from "./images/MacbookPro-Laptop2.jpg";
import MacbookProLaptop3 from "./images/MacbookPro-Laptop3.jpg";
import MacbookAir from "./images/MacbookAir-Laptop.jpg";
import MacbookAir2 from "./images/MacbookAir-Laptop2.jpg";
import DellLaptop from "./images/Dell-Laptop.jpg";
import DellLaptop2 from "./images/Dell-Laptop2.jpg";
import AcerLaptop from "./images/Acer-Laptop.jpg";
import AcerLaptop2 from "./images/Acer-Laptop2.jpg";
import HPLaptop from "./images/HP-Laptop.jpg";
import HPLaptop2 from "./images/HP-Laptop2.jpg";
import LaptopASUS from "./images/ASUS-Laptop.jpg";
import LaptopASUS2 from "./images/ASUS-Laptop2.jpg";

export const listProducts = [
	{
		id: "AA0001",
		category: "Desktop",
		type: "iMac",
		product: "24inch 4.5 Retina Display",
		description:
			"iMac-ChipM1 8-Core CPU & 7-Core GPU 8GB Unified memory 256GB Storage",
		price: 1899,
		image: iMacDesktop2,
		quanity: 1,
		newArrival: true,
	},
	{
		id: "AA0002",
		category: "Desktop",
		type: "iMac",
		product: "24inch 4.5 Retina Display",
		description:
			"iMac-ChipM1 8-Core CPU & 8-Core GPU 16GB Unified memory 256GB Storage",
		price: 2099,
		image: iMacDesktop2,
		quanity: 1,
		newArrival: true,
	},
	{
		id: "AA0003",
		category: "Desktop",
		type: "iMac",
		product: "24inch 4.5 Retina Display",
		description:
			"iMac-ChipM1 8-Core CPU & 8-Core GPU 16GB Unified memory 512GB Storage",
		price: 2299,
		image: iMacDesktop,
		quanity: 1,
	},
	{
		id: "AA0004",
		category: "Desktop",
		type: "iMac",
		product: "24inch 4.5 Retina Display",
		description:
			"iMac-ChipM1 8-Core CPU & 8-Core GPU 16GB Unified memory 1TB Storage",
		price: 2599,
		image: iMacDesktop,
		quanity: 1,
	},
	{
		id: "A10001",
		category: "Desktop",
		type: "iMac",
		product: "24inch 4.5 Retina Display",
		description:
			"iMac-ChipM1 8-Core CPU & 8-Core GPU 24GB Unified memory 256GB Storage",
		price: 2299,
		image: iMacDesktop2,
		quanity: 1,
	},
	{
		id: "A10002",
		category: "Desktop",
		type: "iMac",
		product: "24inch 4.5 Retina Display",
		description:
			"iMac-ChipM1 8-Core CPU & 8-Core GPU 24GB Unified memory 512GB Storage",
		price: 2499,
		image: iMacDesktop,
		quanity: 1,
		onSale: true,
	},
	{
		id: "A10003",
		category: "Desktop",
		type: "iMac",
		product: "24inch 4.5 Retina Display",
		description:
			"iMac-ChipM1 8-Core CPU & 8-Core GPU 24GB Unified memory 1TB Storage",
		price: 2799,
		image: iMacDesktop2,
		quanity: 1,
		newArrival: true,
	},
	{
		id: "A10004",
		category: "Desktop",
		type: "iMac",
		product: "24inch 4.5 Retina Display",
		description:
			"iMac-ChipM1 8-Core CPU & 8-Core GPU 24GB Unified memory 2TB Storage",
		price: 2999,
		image: iMacDesktop,
		quanity: 1,
	},
	{
		id: "A10005",
		category: "Desktop",
		type: "iMac",
		product: "24inch 4.5 Retina Display",
		description:
			"iMac-ChipM1 10-Core CPU & 10-Core GPU 24GB Unified memory 256GB Storage",
		price: 2339,
		image: iMacDesktop2,
		quanity: 1,
		newArrival: true,
	},
	{
		id: "A10006",
		category: "Desktop",
		type: "iMac",
		product: "24inch 4.5 Retina Display",
		description:
			"iMac-ChipM1 10-Core CPU & 10-Core GPU 24GB Unified memory 512GB Storage",
		price: 2669,
		image: iMacDesktop,
		quanity: 1,
		onSale: true,
	},
	{
		id: "A10007",
		category: "Desktop",
		type: "iMac",
		product: "24inch 4.5 Retina Display",
		description:
			"iMac-ChipM1 10-Core CPU & 10-Core GPU 24GB Unified memory 1TB Storage",
		price: 2888,
		image: iMacDesktop,
		quanity: 1,
	},
	{
		id: "AA0005",
		category: "Desktop",
		type: "Mac-Mini",
		product: "MacMini Apple Chip M1",
		description:
			"With 8-Core CPU & 8-Core GPU 8GB Unified memory 256GB Storage",
		price: 929,
		image: MacMini,
		quanity: 1,
		onSale: true,
	},
	{
		id: "AA0006",
		category: "Desktop",
		type: "Mac-Mini",
		product: "MacMini Apple Chip M1",
		description:
			"With 8-Core CPU & 8-Core GPU 16GB Unified memory 256GB Storage",
		price: 1199,
		image: MacMini2,
		quanity: 1,
		newArrival: true,
	},
	{
		id: "AA0007",
		category: "Desktop",
		type: "Mac-Mini",
		product: "MacMini Apple Chip M1",
		description:
			"With 8-Core CPU & 8-Core GPU 16GB Unified memory 512GB Storage",
		price: 1499,
		image: MacMini,
		quanity: 1,
		onSale: true,
	},
	{
		id: "AA0008",
		category: "Desktop",
		type: "Mac-Mini",
		product: "MacMini Apple Chip M1",
		description: "With 8-Core CPU & 8-Core GPU 16GB Unified memory 1TB Storage",
		price: 1899,
		image: MacMini2,
		quanity: 1,
	},
	{
		id: "AA00080",
		category: "Desktop",
		type: "Mac-Mini",
		product: "MacMini Apple Chip M1",
		description: "With 8-Core CPU & 8-Core GPU 16GB Unified memory 2TB Storage",
		price: 2188,
		image: MacMini,
		quanity: 1,
		onSale: true,
	},
	{
		id: "AA00081",
		category: "Desktop",
		type: "Mac-Mini",
		product: "MacMini Apple Chip M1",
		description: "With 8-Core CPU & 8-Core GPU 16GB Unified memory 4TB Storage",
		price: 2688,
		image: MacMini2,
		quanity: 1,
	},
	{
		id: "AA00082",
		category: "Desktop",
		type: "Mac-Mini",
		product: "MacMini Apple Chip M1",
		description:
			"With 10-Core CPU & 10-Core GPU 24GB Unified memory 512SSD Storage",
		price: 2266,
		image: MacMini,
		quanity: 1,
		onSale: true,
	},
	{
		id: "AA00083",
		category: "Desktop",
		type: "Mac-Mini",
		product: "MacMini Apple Chip M1",
		description:
			"With 10-Core CPU & 10-Core GPU 24GB Unified memory 1TB Storage",
		price: 2788,
		image: MacMini2,
		quanity: 1,
	},
	{
		id: "AA00084",
		category: "Desktop",
		type: "Mac-Mini",
		product: "MacMini Apple Chip M1",
		description:
			"With 10-Core CPU & 10-Core GPU 24GB Unified memory 2TB Storage",
		price: 2889,
		image: MacMini,
		quanity: 1,
		onSale: true,
	},
	{
		id: "AA0009",
		category: "Desktop",
		type: "Dell",
		product: "Dell XPS Gen12th",
		description: "With 12-CoreCPU & 3070VGA 16GB Unified memory 512SSD",
		price: 1999,
		image: DellXPSDesktop,
		quanity: 1,
		newArrival: true,
	},
	{
		id: "AA0010",
		category: "Desktop",
		type: "Dell",
		product: "Dell XPS Gen12th",
		description: "With 12-CoreCPU & 3070VGA 32GB Unified memory 512SSD",
		price: 2099,
		image: DellXPSDesktop3,
		quanity: 1,
	},
	{
		id: "AA0011",
		category: "Desktop",
		type: "Dell",
		product: "Dell XPS Gen12th",
		description: "With 12-CoreCPU & 3070VGA 32GB Unified memory 1TBSSD",
		price: 2399,
		image: DellXPSDesktop,
		quanity: 1,
	},
	{
		id: "AA0012",
		category: "Desktop",
		type: "Dell",
		product: "Dell XPS Gen12th",
		description: "With 12-CoreCPU & 3080VGA 32GB Unified memory 2TBSSD",
		price: 3499,
		image: DellXPSDesktop2,
		quanity: 1,
		newArrival: true,
	},
	{
		id: "AA00120",
		category: "Desktop",
		type: "Dell",
		product: "Dell XPS Gen12th",
		description: "With 12-CoreCPU & 2060VGA 16GB Unified memory 512SSD",
		price: 1699,
		image: DellXPSDesktop2,
		quanity: 1,
	},
	{
		id: "AA00121",
		category: "Desktop",
		type: "Dell",
		product: "Dell XPS Gen12th",
		description: "With 12-CoreCPU & 2060VGA 32GB Unified memory 512SSD",
		price: 1799,
		image: DellXPSDesktop3,
		quanity: 1,
		onSale: true,
	},
	{
		id: "AA00122",
		category: "Desktop",
		type: "Dell",
		product: "Dell XPS Gen11th",
		description: "With 12-CoreCPU & 2060VGA 16GB Unified memory 512SSD",
		price: 1499,
		image: DellXPSDesktop2,
		quanity: 1,
	},
	{
		id: "AA00123",
		category: "Desktop",
		type: "Dell",
		product: "Dell XPS Gen11th",
		description: "With 12-CoreCPU & 2060VGA 16GB Unified memory 1TBSSD",
		price: 1879,
		image: DellXPSDesktop2,
		quanity: 1,
		onSale: true,
	},
	{
		id: "AA00124",
		category: "Desktop",
		type: "Dell",
		product: "Dell XPS Gen11th",
		description: "With 12-CoreCPU & 2060VGA 64GB Unified memory 2TBSSD",
		price: 2679,
		image: DellXPSDesktop,
		quanity: 1,
		onSale: true,
	},
	{
		id: "AA0013",
		category: "Desktop",
		type: "HP",
		product: "HP Workstation Gen12th",
		description: "With 12-CoreCPU & 3080VGA 16GB Unified memory 1TBSSD",
		price: 2299,
		image: HPDesktop2,
		quanity: 1,
		newArrival: true,
	},
	{
		id: "AA0014",
		category: "Desktop",
		type: "HP",
		product: "HP Workstation Gen12th",
		description: "With 12-CoreCPU & 3080VGA 32GB Unified memory 1TBSSD",
		price: 2599,
		image: HPDesktop,
		quanity: 1,
	},
	{
		id: "AA0015",
		category: "Desktop",
		type: "HP",
		product: "HP Workstation Gen12th",
		description: "With 12-CoreCPU & 3080VGA 32GB Unified memory 2TBSSD",
		price: 2799,
		image: HPDesktop2,
		quanity: 1,
		onSale: true,
	},
	{
		id: "AA0016",
		category: "Desktop",
		type: "HP",
		product: "HP Workstation Gen12th",
		description: "With 12-CoreCPU & 3080VGA 64GB Unified memory 2TBSSD",
		price: 3299,
		image: HPDesktop,
		quanity: 1,
		newArrival: true,
	},
	{
		id: "AA0017",
		category: "Desktop",
		type: "HP",
		product: "HP Workstation Gen11th",
		description: "With 10-CoreCPU & 2060VGA 16GB Unified memory 512SSD",
		price: 1289,
		image: HPDesktop,
		quanity: 1,
	},
	{
		id: "AA0018",
		category: "Desktop",
		type: "HP",
		product: "HP Workstation Gen11th",
		description: "With 10-CoreCPU & 2060VGA 32GB Unified memory 512SSD",
		price: 1689,
		image: HPDesktop2,
		quanity: 1,
		newArrival: true,
	},
	{
		id: "AA0019",
		category: "Desktop",
		type: "HP",
		product: "HP Workstation Gen11th",
		description: "With 10-CoreCPU & 2060VGA 32GB Unified memory 1TB",
		price: 1889,
		image: HPDesktop,
		quanity: 1,
		onSale: true,
	},
	{
		id: "AA0020",
		category: "Desktop",
		type: "HP",
		product: "HP Workstation Gen11th",
		description: "With 10-CoreCPU & 2060VGA 32GB Unified memory 1TB",
		price: 2099,
		image: HPDesktop,
		quanity: 1,
	},
	{
		id: "AA0021",
		category: "Desktop",
		type: "HP",
		product: "HP Workstation Gen11th",
		description: "With 10-CoreCPU & 2060VGA 32GB Unified memory 2TB",
		price: 2199,
		image: HPDesktop2,
		quanity: 1,
	},
	{
		id: "AA0022",
		category: "Desktop",
		type: "Acer",
		product: "Acer Nitro Gen11th",
		description: "With 10-CoreCPU & 2060VGA 8GB DDRAM4 256SSD",
		price: 1229,
		image: AcerDesktop,
		quanity: 1,
		onSale: true,
	},
	{
		id: "AA00220",
		category: "Desktop",
		type: "Acer",
		product: "Acer Predator Gen12th",
		description: "With 12-CoreCPU & 3080VGA 32GB DDRAM4 1TB",
		price: 3699,
		image: ACERDESKTOPPREDATOR,
		quanity: 1,
		newArrival: true,
	},
	{
		id: "AA0023",
		category: "Desktop",
		type: "Acer",
		product: "Acer Nitro Gen11th",
		description: "With 10-CoreCPU & 2060VGA 16GB DDRAM4 256SSD",
		price: 1489,
		image: AcerDesktop,
		quanity: 1,
	},
	{
		id: "AA0024",
		category: "Desktop",
		type: "Acer",
		product: "Acer Nitro Gen11th",
		description: "With 10-CoreCPU & 2060VGA 16GB DDRAM4 512SSD",
		price: 1689,
		image: AcerDesktop,
		quanity: 1,
		newArrival: true,
	},
	{
		id: "AA0025",
		category: "Desktop",
		type: "Acer",
		product: "Acer Nitro Gen11th",
		description: "With 10-CoreCPU & 2060VGA 32GB DDRAM4 512SSD",
		price: 1889,
		image: AcerDesktop,
		quanity: 1,
		onSale: true,
	},
	{
		id: "AA0026",
		category: "Desktop",
		type: "Acer",
		product: "Acer Nitro Gen12th",
		description: "With 10-CoreCPU & 3060VGA 16GB DDRAM4 512SSD",
		price: 2009,
		image: AcerDesktop,
		quanity: 1,
		newArrival: true,
	},
	{
		id: "AA0027",
		category: "Desktop",
		type: "Acer",
		product: "Acer Nitro Gen12th",
		description: "With 10-CoreCPU & 3060VGA 16GB DDRAM4 512SSD",
		price: 2009,
		image: AcerDesktop,
		quanity: 1,
	},
	{
		id: "AA0028",
		category: "Desktop",
		type: "Acer",
		product: "Acer Nitro Gen12th",
		description: "With 10-CoreCPU & 3060VGA 32GB DDRAM4 1TB",
		price: 2559,
		image: AcerDesktop,
		quanity: 1,
		onSale: true,
	},
	{
		id: "AA0029",
		category: "Desktop",
		type: "Acer",
		product: "Acer Nitro Gen12th",
		description: "With 10-CoreCPU & 3060VGA 32GB DDRAM4 2TB",
		price: 2779,
		image: AcerDesktop,
		quanity: 1,
		onSale: true,
	},
	{
		id: "AA0030",
		category: "Desktop",
		type: "Acer",
		product: "Acer Nitro Gen12th",
		description: "With 10-CoreCPU & 3070VGA 32GB DDRAM4 2TB",
		price: 2999,
		image: AcerDesktop,
		quanity: 1,
	},
	{
		id: "AA0031",
		category: "Desktop",
		type: "Acer",
		product: "Acer Nitro Gen12th",
		description: "With 10-CoreCPU & 3080VGA 64GB DDRAM4 2TB",
		price: 4999,
		image: AcerDesktop,
		quanity: 1,
	},
	{
		id: "AA0032",
		category: "Desktop",
		type: "Asus",
		product: "ASUS ROG Strix Gen11th",
		description: "With 10-CoreCPU & 2060VGA 16GB DDRAM4 512SSD",
		price: 1299,
		image: ASUSDesktop3,
		quanity: 1,
		newArrival: true,
	},
	{
		id: "AA0033",
		category: "Desktop",
		type: "Asus",
		product: "ASUS ROG Strix Gen11th",
		description: "With 10-CoreCPU & 2060VGA 32GB DDRAM4 512SSD",
		price: 1499,
		image: ASUSDesktop2,
		quanity: 1,
	},
	{
		id: "AA0034",
		category: "Desktop",
		type: "Asus",
		product: "ASUS ROG Strix Gen11th",
		description: "With 10-CoreCPU & 2060VGA 32GB DDRAM4 1TB",
		price: 1889,
		image: ASUSDesktop,
		quanity: 1,
		newArrival: true,
	},
	{
		id: "AA0035",
		category: "Desktop",
		type: "Asus",
		product: "ASUS ROG Strix Gen11th",
		description: "With 10-CoreCPU & 2070VGA 32GB DDRAM4 1TB",
		price: 1999,
		image: ASUSDesktop2,
		quanity: 1,
		onSale: true,
	},
	{
		id: "AA0036",
		category: "Desktop",
		type: "Asus",
		product: "ASUS ROG Strix Gen12th",
		description: "With 12-CoreCPU & 3060VGA 16GB DDRAM4 512SSD",
		price: 2099,
		image: ASUSDesktop3,
		quanity: 1,
		onSale: true,
	},
	{
		id: "AA0037",
		category: "Desktop",
		type: "Asus",
		product: "ASUS ROG Strix Gen12th",
		description: "With 12-CoreCPU & 3060VGA 32GB DDRAM4 512SSD",
		price: 2299,
		image: ASUSDesktop3,
		quanity: 1,
	},
	{
		id: "AA0038",
		category: "Desktop",
		type: "Asus",
		product: "ASUS ROG Strix Gen12th",
		description: "With 12-CoreCPU & 3060VGA 32GB DDRAM4 1TB",
		price: 2499,
		image: ASUSDesktop2,
		quanity: 1,
		newArrival: true,
	},
	{
		id: "AA0039",
		category: "Desktop",
		type: "Asus",
		product: "ASUS ROG Strix Gen12th",
		description: "With 12-CoreCPU & 3060VGA 32GB DDRAM4 2TB",
		price: 2599,
		image: ASUSDesktop3,
		quanity: 1,
		newArrival: true,
	},
	{
		id: "AA0040",
		category: "Desktop",
		type: "Asus",
		product: "ASUS ROG Strix Gen12th",
		description: "With 12-CoreCPU & 3060VGA 64GB DDRAM4 2TB",
		price: 2899,
		image: ASUSDesktop2,
		quanity: 1,
	},
	{
		id: "AA0041",
		category: "Desktop",
		type: "Asus",
		product: "ASUS ROG Strix Gen12th",
		description: "With 12-CoreCPU & 3070VGA 32GB DDRAM4 2TB",
		price: 2999,
		image: ASUSDesktop,
		quanity: 1,
		onSale: true,
	},
	{
		id: "AA0042",
		category: "Desktop",
		type: "Asus",
		product: "ASUS ROG Strix Gen12th",
		description: "With 12-CoreCPU & 3080VGA 64GB DDRAM4 4TB",
		price: 4779,
		image: ASUSDesktop,
		quanity: 1,
	},
	{
		id: "AA0043",
		category: "Laptop",
		type: "MacbookPro",
		product: "Apple MacBook Pro 13 M1",
		description: "10-Core CPU & 10-Core GPU 8GB Unified memory 256GB SSD",
		price: 1789,
		image: MacbookProLaptop,
		quanity: 1,
		onSale: true,
	},
	{
		id: "AA0044",
		category: "Laptop",
		type: "MacbookPro",
		product: "Apple MacBook Pro 13 M1",
		description: "10-Core CPU & 10-Core GPU 16GB Unified memory 256GB SSD",
		price: 2189,
		image: MacbookProLaptop2,
		quanity: 1,
		onSale: true,
	},
	{
		id: "AA0045",
		category: "Laptop",
		type: "MacbookPro",
		product: "Apple MacBook Pro 13 M1",
		description: "10-Core CPU & 10-Core GPU 16GB Unified memory 512GB SSD",
		price: 2289,
		image: MacbookProLaptop,
		quanity: 1,
	},
	{
		id: "AA0046",
		category: "Laptop",
		type: "MacbookPro",
		product: "Apple MacBook Pro 13 M1",
		description: "10-Core CPU & 10-Core GPU 24GB Unified memory 512GB SSD",
		price: 2369,
		image: MacbookProLaptop,
		quanity: 1,
	},
	{
		id: "AA0047",
		category: "Laptop",
		type: "MacbookPro",
		product: "Apple MacBook Pro 13 M1",
		description: "10-Core CPU & 10-Core GPU 24GB Unified memory 1TB SSD",
		price: 2569,
		image: MacbookProLaptop2,
		quanity: 1,
		newArrival: true,
	},
	{
		id: "AA0048",
		category: "Laptop",
		type: "MacbookPro",
		product: "Apple MacBook Pro 15 M1",
		description: "10-Core CPU & 10-Core GPU 32GB Unified memory 2TB SSD",
		price: 3769,
		image: MacbookProLaptop3,
		quanity: 1,
	},
	{
		id: "AA0049",
		category: "Laptop",
		type: "MacbookPro",
		product: "Apple MacBook Pro 13 M1",
		description: "10-Core CPU & 10-Core GPU 24GB Unified memory 2TB SSD",
		price: 2769,
		image: MacbookProLaptop2,
		quanity: 1,
		newArrival: true,
	},
	{
		id: "AA0050",
		category: "Laptop",
		type: "MacbookPro",
		product: "Apple MacBook Pro 15 M1",
		description: "12-Core CPU & 12-Core GPU 32GB Unified memory 2TB SSD",
		price: 4669,
		image: MacbookProLaptop3,
		quanity: 1,
	},
	{
		id: "AA0051",
		category: "Laptop",
		type: "MacbookPro",
		product: "Apple MacBook Pro 13 M1",
		description: "12-Core CPU & 12-Core GPU 32GB Unified memory 4TB SSD",
		price: 4469,
		image: MacbookProLaptop,
		quanity: 1,
		newArrival: true,
	},
	{
		id: "AA00521",
		category: "Laptop",
		type: "MacbookAir",
		product: "Apple MacBook Air 13 M1",
		description: "10-Core CPU & 10-Core GPU 8GB Unified memory 256 SSD",
		price: 1229,
		image: MacbookAir,
		quanity: 1,
		onSale: true,
	},
	{
		id: "AA0052",
		category: "Laptop",
		type: "MacbookAir",
		product: "Apple MacBook Air 13 M1",
		description: "10-Core CPU & 10-Core GPU 16GB Unified memory 256 SSD",
		price: 1429,
		image: MacbookAir2,
		quanity: 1,
	},
	{
		id: "AA0053",
		category: "Laptop",
		type: "MacbookAir",
		product: "Apple MacBook Air 13 M1",
		description: "10-Core CPU & 10-Core GPU 16GB Unified memory 512 SSD",
		price: 1829,
		image: MacbookAir2,
		quanity: 1,
		onSale: true,
	},
	{
		id: "AA0054",
		category: "Laptop",
		type: "MacbookAir",
		product: "Apple MacBook Air 13 M1",
		description: "10-Core CPU & 10-Core GPU 24GB Unified memory 512 SSD",
		price: 2029,
		image: MacbookAir2,
		quanity: 1,
	},
	{
		id: "AA0055",
		category: "Laptop",
		type: "MacbookAir",
		product: "Apple MacBook Air 13 M1",
		description: "10-Core CPU & 10-Core GPU 24GB Unified memory 1TB SSD",
		price: 2429,
		image: MacbookAir,
		quanity: 1,
		newArrival: true,
	},
	{
		id: "AA0056",
		category: "Laptop",
		type: "MacbookAir",
		product: "Apple MacBook Air 13 M1",
		description: "10-Core CPU & 10-Core GPU 24GB Unified memory 2TB SSD",
		price: 2629,
		image: MacbookAir,
		quanity: 1,
	},
	{
		id: "AA0057",
		category: "Laptop",
		type: "MacbookAir",
		product: "Apple MacBook Air 13 M1",
		description: "10-Core CPU & 10-Core GPU 32GB Unified memory 2TB SSD",
		price: 3019,
		image: MacbookAir2,
		quanity: 1,
		newArrival: true,
	},
	{
		id: "AA0058",
		category: "Laptop",
		type: "MacbookAir",
		product: "Apple MacBook Air 13 M1",
		description: "10-Core CPU & 10-Core GPU 32GB Unified memory 4TB SSD",
		price: 3889,
		image: MacbookAir2,
		quanity: 1,
	},
	{
		id: "AA0059",
		category: "Laptop",
		type: "MacbookAir",
		product: "Apple MacBook Air 13 M2",
		description: "10-Core CPU & 10-Core GPU 16GB Unified memory 512 SSD",
		price: 1889,
		image: MacbookAir2,
		quanity: 1,
		onSale: true,
	},
	{
		id: "AA0060",
		category: "Laptop",
		type: "MacbookAir",
		product: "Apple MacBook Air 13 M2",
		description: "10-Core CPU & 10-Core GPU 32GB Unified memory 512 SSD",
		price: 2489,
		image: MacbookAir2,
		quanity: 1,
	},
	{
		id: "AA0061",
		category: "Laptop",
		type: "Dell XPS",
		product: "Dell XPS Gen11th 13inch",
		description: "With 12-Core CPU & 3060VGA 8GB Memory 256 SSD",
		price: 1689,
		image: DellLaptop,
		quanity: 1,
		onSale: true,
	},
	{
		id: "AA0062",
		category: "Laptop",
		type: "Dell XPS",
		product: "Dell XPS Gen11th 13inch",
		description: "With 12-Core CPU & 3060VGA 16GB Memory 256 SSD",
		price: 1999,
		image: DellLaptop,
		quanity: 1,
		onSale: true,
	},
	{
		id: "AA0063",
		category: "Laptop",
		type: "Dell XPS",
		product: "Dell XPS Gen11th 13inch",
		description: "With 12-Core CPU & 3060VGA 32GB Memory 512 SSD",
		price: 2899,
		image: DellLaptop,
		quanity: 1,
		newArrival: true,
	},
	{
		id: "AA0064",
		category: "Laptop",
		type: "Dell XPS",
		product: "Dell XPS Gen11th 13inch",
		description: "With 12-Core CPU & 3060VGA 32GB Memory 1TB SSD",
		price: 3099,
		image: DellLaptop2,
		quanity: 1,
		newArrival: true,
	},
	{
		id: "AA0065",
		category: "Laptop",
		type: "Dell XPS",
		product: "Dell XPS Gen11th 13inch",
		description: "With 12-Core CPU & 3060VGA 32GB Memory 2TB SSD",
		price: 3299,
		image: DellLaptop2,
		quanity: 1,
	},
	{
		id: "AA0066",
		category: "Laptop",
		type: "Laptop-Acer",
		product: "Acer Nitro 6 Core i7 Gen11th",
		description: "With 12-Core CPU & 3060VGA 16GB Memory 512 SSD",
		price: 1999,
		image: AcerLaptop,
		quanity: 1,
		newArrival: true,
	},
	{
		id: "AA0067",
		category: "Laptop",
		type: "Laptop-Acer",
		product: "Acer Nitro 6 Core i7 Gen11th",
		description: "With 12-Core CPU & 3060VGA 16GB Memory 1TB SSD",
		price: 2229,
		image: AcerLaptop,
		quanity: 1,
	},
	{
		id: "AA0068",
		category: "Laptop",
		type: "Laptop-Acer",
		product: "Acer Nitro 6 Core i7 Gen11th",
		description: "With 12-Core CPU & 3060VGA 32GB Memory 1TB SSD",
		price: 2429,
		image: AcerLaptop,
		quanity: 1,
	},
	{
		id: "AA0069",
		category: "Laptop",
		type: "Laptop-Acer",
		product: "Acer Nitro 6 Core i7 Gen11th",
		description: "With 12-Core CPU & 3060VGA 32GB Memory 2TB SSD",
		price: 2889,
		image: AcerLaptop,
		quanity: 1,
		onSale: true,
	},
	{
		id: "AA0070",
		category: "Laptop",
		type: "Laptop-Acer",
		product: "Acer Predator Core i7 Gen12th",
		description: "With 12-Core CPU & 3070VGA 16GB Memory 1TB SSD",
		price: 3009,
		image: AcerLaptop2,
		quanity: 1,
		onSale: true,
	},
	{
		id: "AA0071",
		category: "Laptop",
		type: "Laptop-Acer",
		product: "Acer Predator Core i7 Gen12th",
		description: "With 12-Core CPU & 3070VGA 32GB Memory 1TB SSD",
		price: 3339,
		image: AcerLaptop2,
		quanity: 1,
		newArrival: true,
	},
	{
		id: "AA0072",
		category: "Laptop",
		type: "Laptop-Acer",
		product: "Acer Predator Core i7 Gen12th",
		description: "With 12-Core CPU & 3080VGA 32GB Memory 2TB SSD",
		price: 3559,
		image: AcerLaptop2,
		quanity: 1,
		onSale: true,
	},
	{
		id: "AA0073",
		category: "Laptop",
		type: "HP-Omen",
		product: "HP Omen Core i7 Gen11th",
		description: "With 10-Core CPU & 3060VGA 16GB Memory 1TB SSD",
		price: 1889,
		image: HPLaptop,
		quanity: 1,
		newArrival: true,
	},
	{
		id: "AA0074",
		category: "Laptop",
		type: "HP-Omen",
		product: "HP Omen Core i7 Gen11th",
		description: "With 10-Core CPU & 3060VGA 32GB Memory 1TB SSD",
		price: 2009,
		image: HPLaptop,
		quanity: 1,
		newArrival: true,
	},
	{
		id: "AA0075",
		category: "Laptop",
		type: "HP-Omen",
		product: "HP Omen Core i7 Gen12th",
		description: "With 10-Core CPU & 3070VGA 16GB Memory 1TB SSD",
		price: 2249,
		image: HPLaptop2,
		quanity: 1,
	},
	{
		id: "AA0076",
		category: "Laptop",
		type: "HP-Omen",
		product: "HP Omen Core i7 Gen12th",
		description: "With 10-Core CPU & 3070VGA 32GB Memory 1TB SSD",
		price: 2549,
		image: HPLaptop2,
		quanity: 1,
		onSale: true,
	},
	{
		id: "AA0077",
		category: "Laptop",
		type: "ASus-Zenbook",
		product: "ASUS Zenbook 14 OLED Gen12th",
		description: "With 10-Core CPU & 3060VGA 16GB Memory 1TB SSD",
		price: 1889,
		image: LaptopASUS,
		quanity: 1,
		onSale: true,
	},
	{
		id: "AA0078",
		category: "Laptop",
		type: "ASus-Zenbook",
		product: "ASUS Zenbook 14 OLED Gen12th",
		description: "With 10-Core CPU & 3060VGA 32GB Memory 1TB SSD",
		price: 2089,
		image: LaptopASUS,
		quanity: 1,
		onSale: true,
	},
	{
		id: "AA0079",
		category: "Laptop",
		type: "ASus-Zenbook",
		product: "ASUS Zenbook 14 OLED Gen12th",
		description: "With 10-Core CPU & 3060VGA 32GB Memory 2TB SSD",
		price: 2469,
		image: LaptopASUS2,
		quanity: 1,
	},
	{
		id: "AA0080",
		category: "Laptop",
		type: "ASus-Zenbook",
		product: "ASUS Zenbook 14 OLED Gen12th",
		description: "With 10-Core CPU & 3070VGA 32GB Memory 1TB SSD",
		price: 2559,
		image: LaptopASUS2,
		quanity: 1,
		newArrival: true,
	},
];

// export function getListProducts() {
// 	return myFunction(listProducts).filter((g) => g);
// }

export function getListProducts() {
	return listProducts.filter((g) => g);
}
const myFunction = function ShuffleListProducts(array) {
	let curId = array.length;
	// There remain elements to shuffle
	while (0 !== curId) {
		// Pick a remaining element
		let randId = Math.floor(Math.random() * curId);
		curId -= 1;
		// Swap it with the current element.
		let tmp = array[curId];
		array[curId] = array[randId];
		array[randId] = tmp;
	}
	console.log("ShuffleListProducts clicked");
	return array;
};
